<!-- Banner ou separador -->
<img src="https://capsule-render.vercel.app/api?type=waving&color=0F2027&height=100&section=header"/>

<h1 align="center">👋 Olá! Eu sou o Claudio Lucas</h1>
<h3 align="center">💻 Desenvolvedor Backend • Amante de tecnologia</h3>

---

## 👨‍💻 Sobre Mim

Sou um desenvolvedor apaixonado por criar soluções inovadoras e impactantes. Atualmente trabalho como **Backend Developer** na **Global Technologies Services**, criando APIs, otimizando bancos de dados e colaborando com times multifuncionais.

- 🎓 Cursando **Análise e Desenvolvimento de Sistemas**
- 🚀 Apaixonado por tecnologia, backend, microserviços e boas práticas
- 🧠 Sempre em aprendizado e evolução

---

## 🛠️ Tecnologias & Ferramentas

<div style="display: flex; gap: 10px;">
  
![HTML5](https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white)
![CSS3](https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white)
![JavaScript](https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black)
![TypeScript](https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white)
![React](https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB)
![Next.js](https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=nextdotjs&logoColor=white)
![Node.js](https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=nodedotjs&logoColor=white)
![Express](https://img.shields.io/badge/Express.js-404D59?style=for-the-badge)
![MongoDB](https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white)
![PostgreSQL](https://img.shields.io/badge/PostgreSQL-4169E1?style=for-the-badge&logo=postgresql&logoColor=white)
![Docker](https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=docker&logoColor=white)
![Git](https://img.shields.io/badge/Git-F05032?style=for-the-badge&logo=git&logoColor=white)

</div>

---

## 🌱 Tecnologias que estou aprendendo

![Python](https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=python&logoColor=white)
![Flask](https://img.shields.io/badge/Flask-black?style=for-the-badge&logo=flask&logoColor=white)
![Firebase](https://img.shields.io/badge/Firebase-FFCA28?style=for-the-badge&logo=firebase&logoColor=black)

---

## 📈 GitHub Stats

<div align="center">

![Claudio's GitHub Stats](https://github-readme-stats.vercel.app/api?username=maximonGamer&show_icons=true&theme=radical)
![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=maximonGamer&layout=compact&theme=radical)

</div>

---

## 📚 Formação

| Curso | Plataforma | Status |
|-------|------------|--------|
| Análise e Desenvolvimento de Sistemas | Universidade Braz Cubas | Em andamento |
| Programação | Fundação Bradesco | Concluído |
| Full Stack | Rocketseat / Independente | Em progresso |

---

## 🤝 Conecte-se comigo

[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/claudio-lucas-henrique-francisco-ribeiro-1a8148346)
[![Instagram](https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white)](https://www.instagram.com/claudio_ribeirofh)
[![WhatsApp](https://img.shields.io/badge/WhatsApp-25D366?style=for-the-badge&logo=whatsapp&logoColor=white)](https://wa.me/11998115005)
[![Gmail](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:lucasclaudio830@gmail.com)

---

## 💻 Sistemas Operacionais

![Android](https://img.shields.io/badge/Android-3DDC84?style=for-the-badge&logo=android&logoColor=white)
![Windows](https://img.shields.io/badge/Windows-0078D6?style=for-the-badge&logo=windows&logoColor=white)

---

⭐ *Se gostou do meu perfil, não esqueça de me seguir que eu sigo de volta!*

<img src="https://capsule-render.vercel.app/api?type=waving&color=0F2027&height=100&section=footer"/>
